### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by Sneakyp33t** [StackHive/DragDropInterface#2]
I'm not able to run the demo properly. When I try to run the demo, in google chrome, I get a few errors. Here are pictures of the error I am getting
![error1](https://cloud.githubusercontent.com/assets/13798913/16423538/08c8b474-3d22-11e6-97d7-0a680811b0a0.jpg)
![error2](https://cloud.githubusercontent.com/assets/13798913/16423539/08cb0a94-3d22-11e6-8c02-6da1bda0f6d0.jpg)

**Comment by Kastlebrick** [comment]
If you haven't already figured it out, it looks like you are running into this issue because you are trying to run this from your desktop, and not from a server/website. 

For example, the first error is the stylesheet URL is href="//maxcdn.bootstrapcdn.com.....  which would normally resolved to http: or https://maxcdn.bootstrapcdn.com if you were hosting this on a website, but because you are trying to run it from your desktop it is trying to load it as a file file://maxcdn.bootstrapcdn.com.... 

Secondly, as the errors state, there is an 'Uncaught SecurityError' which, in a nutshell, is a Chrome security feature.  Protocols, domains and ports must match.
example: `<protocol>://<domain>:<port>`
meaning: `http://www.example.com:80`

Try hosting it on a webserver & site.
